name: "release"
version: "0.3.4"
usage: "Determines the charts next release number"
description: |-
  This plugin will use environment variables and git history to divine the next chart version.
  It will also optionally update the image tag in the values.yaml file.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/helm-release"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
